
name: P2pNet.Base Build/Test

env:
  SUBPROJECT: P2pNet.Base

on:
  push:
    branches: [ master ]
    paths:
    - 'src/P2pNet.Base/**'
    - 'tests/P2pNet.Base.Tests/**'

# Would really like to do this:
#    paths:
#    - 'src/${{env.SUBPROJECT}}/**'
#    - 'tests/${{env.SUBPROJECT}}.Tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Checkout Target
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout Apian dependencies (UniLog)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/UniLog
        path: UniLog

    - name: Restore dependencies
      run: dotnet restore
      working-directory: main

    - name: Default badges
      run: |
        cp -v ./main/.github/badges/badge_branchcoverage_none.svg  ./main/.github/badges/$SUBPROJECT_linecoverage.svg
        cp -v ./main/.github/badges/badge_branchcoverage_none.svg ./main/.github/badges/$SUBPROJECT_branchcoverage.svg

    - name: Build
      run: dotnet build ./src/$SUBPROJECT --configuration Release --no-restore
      working-directory: main

    - name: Test
      run: >
        dotnet test ./tests/$SUBPROJECT.Tests
        --no-restore --verbosity normal
        -p:CollectCoverage=true -p:CoverletOutput="./coverage/"
        -p:CoverletOutputFormat=cobertura -p:Include="[$SUBPROJECT]*"
      working-directory: main

    - name: Commit Badges
      run: |
        cp -v ./main/tests/${{env.SUBPROJECT}}.Tests/coverage/reports/badge_linecoverage.svg ./main/.github/badges/$SUBPROJECT_linecoverage.svg
        cp -v ./main/tests/${{env.SUBPROJECT}}.Tests/coverage/reports/badge_branchcoverage.svg ./main/.github/badges/$SUBPROJECT_branchcoverage.svg
        git config --global user.name "ApianFrameworkPackageAccess"
        git config --global user.email "apian-framework-machine@bigfattail.com"
        git add ./main/.github/badges/$SUBPROJECT_linecoverage.svg
        git add ./main/.github/badges/$SUBPROJECT_branchcoverage.svg
        git commit -m "$SUBPROJECT coverage badges"
        git push

    # - name: Where am I?
    #   run: |
    #     echo Pwd: "$(pwd)"
    #     echo ls: "$(ls)"
    #     echo Way down: "$(ls ./main/tests/P2pNet.Base.Tests/coverage/reports/)"

    # This works, but there's nothing useful to do with the badge, 'cause it's zipped
    # - name: Upload Coverage Badge
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{env.SUBPROJECT}}_badge.svg
    #     path: ./main/tests/${{env.SUBPROJECT}}.Tests/coverage/reports/badge_linecoverage.svg

