
name: Build-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Checkout Target
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout Apian dependencies (UniLog)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/UniLog
        path: UniLog

    - name: Restore dependencies
      run: dotnet restore
      working-directory: main

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: main

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: main